config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  devise_for :users
  get '/home/about' => "homes#about", as: "about"
  post '/users/:id', to: 'books#edit'
  post '/users/:id/edit', to: 'users#update'


  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

   # titleカラムのバリデーション
  validates :title, presence: { message: "can't be blank" }

  # bodyカラムのバリデーション
  validates :body, presence: { message: "can't be blank" }, length: { maximum: 200, message: "is too long (maximum is 200 characters" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable

  has_many :books, dependent: :destroy


  # nameカラムのバリデーション
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }

  # introductionカラムのバリデーション
  validates :introduction, length: { maximum: 50 }


  attribute :introduction

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about] # top, about の2つのアクションのみ、ログイン無しでもアクセス可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end


  def after_sign_out_path_for(resource)
    root_path
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]


  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      redirect_to @book, notice: 'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all # 本のリストを取得
      @users = User.all  # ユーザーのリストを取得
      render :index # index ビューを再表示
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @users = User.all
  end

  def show
    @book = Book.find(params[:id])  # Bookを先に取得
    @user = @book.user              # Bookに関連するUserを取得
    @books = @user.books            # そのUserが所有している本の一覧を取得
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully deleted.'
  end


    # 投稿データのストロングパラメータ
  private

  def set_book
    @book = Book.find(params[:id])
  end

  def authorize_user!
    redirect_to books_path, alert: 'You are not authorized to edit this book.' unless current_user == @book.user
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authorize_user!, only: [:edit, :update]


  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    # @user = User.find(params[:id])
    # @userはbefore_actionでセットされているので、ここでは特に何もしなくて大丈夫です
  end

  def index
    @users = User.all
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id), notice: "You have updated user successfully."
    else
    # バリデーションエラーがある場合、エラーメッセージを表示して編集画面に戻る
      render :edit
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user!
    unless current_user.id == @user.id
      flash[:alert] = "他のユーザーのプロフィールを編集する権限がありません。"
      redirect_to user_path(current_user)
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-12 col-md-8 col-lg-5 px-5'>

      <h2 class="mt-3">Editing Book</h2>
      <% if @book && @book.errors.any? %>
        <h3 class="mt-3"><%=@book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>




      <%= form_with model: @book, class: "mt-3" do |f| %>
        <label>Title</label>
        <%= f.text_field :title, autofocus: true, class: "form-control" %>

        <label class="mt-2">Opinion</label>
        <%= f.text_area :body, autofocus: true, class: "form-control" %>

        <%= f.submit 'Update Book', class: "btn btn-success mt-2" %>
      <% end %>
      <p class="mt-3"><%= link_to 'Show', book_path(@book) %>
       |
       <%=link_to 'Back', books_path %></p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<!--User info-->
<div class='container px-5 px-sm-0'>

  <% if @book && @book.errors.any? %>
    <h3 class="mt-3"><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

</div>


<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class='table'>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>

        <div class='row'>
          <% if @user == current_user %>
            <%= link_to raw('<i class="fa-solid fa-user-gear"></i>'), edit_user_path(@user), class: "btn btn-outline-secondary btn-block mt-3"%>
          <% else %>
            <%= link_to raw('<i class="fa-solid fa-user-gear"></i>'), user_path(current_user.id), class: "btn btn-info btn-sm btn-block mb-3" %>
          <% end %>
        </div>


<!--本の新規登録-->


      <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new, url: books_path, class: "mt-3" do |f| %>
        <label>Title</label>
        <%= f.text_field :title, class: "form-control" %>

        <label class="mt-2">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>

        <%= f.submit 'Create Book', class: "btn btn-success mt-2" %>
      <% end %>
    </div>


<!--ユーザー一覧-->


    <div class='col-md-8 offset-md-1'>
      <h2 class="mt-3">Books</h2>

      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(80,80)), user_path(book.user) %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>
<p>/bookers2/app/views/users/show.html.erbここに移動しました。</p>

app/views/books/show.html.erb
<!--User info-->

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class='table'>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>

        <div class='row'>
            <%= link_to raw('<i class="fa-solid fa-user-gear"></i>'), edit_user_path(@user), class: "btn btn-outline-secondary btn-block mt-3"%>
        </div>


<!--本の新規登録-->


      <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new, url: books_path, class: "mt-3" do |f| %>
        <label>Title</label>
        <%= f.text_field :title, class: "form-control" %>

        <label class="mt-2">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>

        <%= f.submit 'Create Book', class: "btn btn-success mt-2" %>
      <% end %>
    </div>


<!--投稿した本の情報-->


    <div class='col-md-8 offset-md-1'>
      <h2 class="mt-3">Book detail</h2>

      <table class='table table-hover table-inverse'>
        <tbody>
          <tr>
            <td><%= image_tag @book.user.get_profile_image(100,100) %><br><%= link_to @user.name, user_path(@user) %></td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class: 'btn btn-success' %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: 'btn btn-danger' %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>in <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions<p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
	   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	     <div class="container">
	       <a class="navbar-brand" href="/"><span>Bookers</span></a>
	       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarNavDropdown">
	        <ul class="navbar-nav ml-auto">
	          <% if user_signed_in? %>
	           <li>
	            <%= link_to user_path(current_user), class:"nav-link text-light" do%>
	             <i class="fa-solid fa-house"></i> Home
	            <% end %>
	           </li>
	           <li>
	            <%= link_to users_path, class:"nav-link text-light" do %>
	             <i class="fa-solid fa-users"></i> Users
	            <% end %>
	           </li>

	           <li>
	            <%= link_to books_path, class:"nav-link text-light" do %>
	             <i class="fa-solid fa-book-open"></i> Books
	            <% end %>
	           </li>

	           <li>
	            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
	             <i class="fa-solid fa-right-from-bracket"></i> Log out
	            <% end %>
	           </li>


	          <% else %>

            <li>
              <%= link_to root_path, class:"nav-link text-light" do%>
               <i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>

            <li>
              <%= link_to about_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-link"></i> About
              <% end %>
            </li>

            <li>
              <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-user-plus"></i> Sign up
              <% end %>
            </li>

            <li>
              <%= link_to new_user_session_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-right-to-bracket"></i> Log in
              <% end %>
            </li>

	           <% end %>
            </ul>
           </div>
         </div>
      </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/023bcd1c80.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>   <!-- ここを追記 -->
    <main>                           <!-- ここを追記 -->
      <% flash.each do |key, value| %>
        <div>
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </main>                          <!-- ここを追記 -->
    <%= render 'layouts/footer' %>   <!-- ここを追記 -->
  </body>
</html>

app/views/users/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-5'>

      <h2 class='mt-3'>User info</h2>
      <% if @user && @user.errors.any? %>
        <h3 class="mt-3"><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @user do |f| %>

      <label for="inputName">Name</label><br>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"" %><br>

      <label class="mt-3" >Image</label><br>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>

      <label class="mt-3" >Introduction</label><br>
      <%= f.text_area :introduction %><br>

      <%= f.submit 'Update User', class: "btn mt-2", style: "background-color: gray; color: white;" %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--User info-->

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class='table'>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>

        <div class='row'>
          <% if @user == current_user %>
            <%= link_to raw('<i class="fa-solid fa-user-gear"></i>'), edit_user_path(@user), class: "btn btn-outline-secondary btn-block mt-3"%>
          <% else %>
            <%= link_to raw('<i class="fa-solid fa-user-gear"></i>'), user_path(current_user.id), class: "btn btn-info btn-sm btn-block mb-3" %>
          <% end %>
        </div>


<!--本の新規登録-->


      <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new, url: books_path, class: "mt-3" do |f| %>
        <label>Title</label>
        <%= f.text_field :title, class: "form-control" %>

        <label class="mt-2">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>

        <%= f.submit 'Create Book', class: "btn btn-success mt-2" %>
      <% end %>
    </div>


<!--ユーザー一覧-->


    <div class='col-md-8 offset-md-1'>
      <h2 class="mt-3">Users</h2>

      <table class='table'>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(80,80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--User info-->

<!--# app/views/users/show.html.erbを変更-->
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class='table'>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>

        <div class='row'>
          <%= link_to raw('<i class="fa-solid fa-user-gear"></i>'), edit_user_path(@user), class: "btn btn-outline-secondary btn-block mt-3"%>
        </div>


<!--本の新規登録-->


      <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new, url: books_path, class: "mt-3" do |f| %>
        <label>Title</label>
        <%= f.text_field :title, class: "form-control" %>

        <label class="mt-2">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>

        <%= f.submit 'Create Book', class: "btn btn-success mt-2" %>
      <% end %>
    </div>


<!--今までに投稿した本の一覧-->

    <div class='col-md-8 offset-md-1'>
      <h2 class="mt-3">Books</h2>

      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(@user.get_profile_image(100, 100)), user_path(book.user) %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>